{
    "i18n.not_found": "The translation value corresponding to key ${name} was not found. Please check if the translation file is complete.",
    "main.info.python_version": "The Python version you are using is ${major}.${minor}.${patch},",
    "main.info.supported_version": "but this program requires the use of Python version 3.9 or above, please replace it in a timely manner.",
    "init.info.checking": "Performing pre-running checks...",
    "init.info.running_with_cert": "Starting main control with certificates...",
    "init.info.running_without_cert": "Starting main control without certificates...",
    "init.info.service_port": "Server listening on ${port}.",
    "init.info.reset_data": "The data has been reset.",
    "init.warning.received_report": "Received report, redirect record: ${urls}, error message: ${error}",
    "init.info.stoped": "The main control has been successfully closed.",
    "utils.info.calculate_filelist": "The file list calculation was successful and has been saved locally.",
    "upstream.info.fetch_git_repo": "Syncing ${url} remote repository...",
    "upstream.info.fetch_git_repo_success": "Remote repository ${url} synchronization completed.",
    "response.400.unsupported_media_type": "Unsupported Media Type",
    "response.401.no_permission": "No Permission",
    "response.401.no_auth": "No Authorization",
    "response.403.node_is_banned": "Node is banned, reason: ${reason}",
    "response.404.not_found": "Not Found",
    "response.404.node_not_found": "Node Not Found",
    "socketio.debug.connect_failed_token": "Client ${sid} connection failed (reason: token not submitted)",
    "socketio.debug.connect_failed_authentication": "Client ${sid} connection failed (reason: authentication error)",
    "socketio.message.welcome": "Welcome to iodine@home, this project is already at https://github.com/ZeroNexis/iodine-at-home open source and looks forward to your contributions and support.",
    "socketio.debug.disconnect": "Client ${sid} disconnected.",
    "socketio.debug.abnormal_disconnect": "${sid} disconnected abnormally and has been removed from the online node list",
    "socketio.return.node_not_found": "ERROR: Node does not seem to exist, please check configuration file.",
    "socketio.return.node_is_online": "ERROR: Node is already online, please check configuration file",
    "socketio.message.version_tips": "The current version is outdated, it is recommended to upgrade to version v${version} or higher.",
    "socketio.debug.enable": "Node ${id} goes online (measured bandwidth: ${bandwidth})",
    "socketio.message.trust_low": "Node trust is too low. Please keep it stable online.",
    "socketio.debug.measure_low": "${id} speed measurement too low (measurement bandwidth: ${bandwidth})",
    "socketio.return.measure_low": "ERROR: The measured bandwidth is less than 10Mbps (measured as ${bandwidth}), please try again to go online.",
    "socketio.debug.measure_error": "The speed measurement of node ${id} did not pass (Error: ${bandwidth})",
    "socketio.return.measure_error": "ERROR: ${bandwidth}",
    "socketio.debug.keep_alive_success": "Node ${id} keeps alive (hits: ${hits} times | requested data: ${bytes})",
    "socketio.debug.disable_failed_not_found": "A node attempted to disable the cluster but failed (reason: node does not exist)",
    "socketio.debug.disable_success": "Node ${id} disables cluster.",
    "socketio.debug.disable_failed_not_online": "Node ${id} failed to attempt to disable the cluster (reason: node is not enabled)"
}