{
    "i18n.not_found": "未找到 ${name} 键对应翻译值，请检查翻译文件是否完整。",
    "main.info.python_version": "你使用的 Python 版本是 ${major}.${minor}.${patch}，",
    "main.info.supported_version": "而该程序要求使用 3.9 版本及以上的 Python，请及时更换。",
    "init.info.checking": "正在进行运行前检查...",
    "init.info.running_with_cert": "使用证书启动主控中...",
    "init.info.running_without_cert": "使用普通模式启动主控中...",
    "init.info.service_port": "正在端口 ${port} 上监听服务器。",
    "init.info.reset_data": "已重置数据。",
    "init.warning.received_report": "收到举报, 重定向记录: ${urls}，错误信息: ${error}",
    "init.info.stoped": "主控已经成功关闭。",
    "utils.info.calculate_filelist": "文件列表计算成功，已保存至本地。",
    "upstream.info.fetch_git_repo": "正在同步 ${url} 远程仓库",
    "upstream.info.fetch_git_repo_success": "远程仓库 ${url} 同步完成",
    "response.400.unsupported_media_type": "不支持的媒体类型",
    "response.401.no_permission": "没有权限",
    "response.401.no_auth": "没有授权",
    "response.403.node_is_banned": "节点被封禁，原因: ${reason}",
    "response.404.not_found": "未找到",
    "response.404.node_not_found": "未找到节点",
    "socketio.debug.connect_failed_token": "客户端 ${sid} 连接失败（原因: 未提交 token 令牌）",
    "socketio.debug.connect_failed_authentication": "客户端 ${sid} 连接失败（原因: 认证出错）",
    "socketio.message.welcome": "欢迎使用 iodine@home，本项目已在 https://github.com/ZeroNexis/iodine-at-home 开源，期待您的贡献与支持。",
    "socketio.debug.disconnect": "客户端 ${sid} 断开了连接",
    "socketio.debug.abnormal_disconnect": "${sid} 异常断开连接，已从在线列表中删除",
    "socketio.return.node_not_found": "错误: 节点似乎并不存在，请检查配置文件",
    "socketio.return.node_is_online": "错误: 节点已经在线，请检查配置文件",
    "socketio.message.version_tips": "当前版本已过时，推荐升级到 v${version} 或以上版本。",
    "socketio.debug.enable": "节点 ${id} 上线（测量带宽: ${bandwidth}）",
    "socketio.message.trust_low": "节点信任度过低，请保持稳定在线。",
    "socketio.debug.measure_low": "${id} 测速未通过（测量带宽: {bandwidth}）",
    "socketio.return.measure_low": "错误: 测量带宽小于 10Mbps，（测量得 ${bandwidth}），请重试尝试上线",
    "socketio.debug.measure_error": "${id} 测速未通过（错误: ${bandwidth[1]}）",
    "socketio.return.measure_error": "错误: ${bandwidth}",
    "socketio.debug.keep_alive_success": "节点 ${id} 保活（请求数: ${hits} 次 | 请求数据量: ${bytes}）",
    "socketio.debug.disable_failed_not_found": "某节点尝试禁用集群失败（原因: 节点不存在）",
    "socketio.debug.disable_success": "节点 ${id} 禁用集群",
    "socketio.debug.disable_failed_not_online": "节点 ${id} 尝试禁用集群失败（原因: 节点没有启用）"
}